### ISSUE TITLE
Can someone help write me a config?

### ISSUE THREAD

**Issue by SunburntRock89** [ArsenArsen/KShare#59]
I need the config to do this ![](http://dash.works.wtf/oh/wait/no/it/doesnt/a07c6.png)

I tried writing one myself, but failed miserably after 12 attempts.

**Comment by ArsenArsen** [comment]
We can't do anything without API documentation.

**Comment by SunburntRock89** [comment]
we'll, that practically is the api, it returns the image as url, in a json object

**Comment by ArsenArsen** [comment]
That's the response, not the request. We can't do anything without knowing how the request is done.

**Comment by SunburntRock89** [comment]
No, that is the request, that is exactly what you send to the server

**Comment by SunburntRock89** [comment]
with file being the file

**Comment by SunburntRock89** [comment]
the request is the image, the response is just url

**Comment by ArsenArsen** [comment]
Is the backend behind that site Pxl? From a quick look around it seems so.

**Comment by SunburntRock89** [comment]
Maybe 😉

**Comment by ArsenArsen** [comment]
that's not helping..

**Comment by SunburntRock89** [comment]
(that means yes)

**Comment by ArsenArsen** [comment]
```json
{
    "name": "squaddy",
    "target": "https://i.squaddy.xyz/api/upload",
    "format": "multipart-form-data",
    "body": [
        {
            "_Content-Type" :"/%contenttype/",
            "filename": "/image.%format/",
            "name": "file",
            "body": "/%imagedata"
        }
    ],
    "return": ".url"
}
```
Should be it.

**Comment by SunburntRock89** [comment]
thanks

**Comment by SunburntRock89** [comment]
are you sure about that? There's no upload token or user, and file isn't being sent either

**Comment by ArsenArsen** [comment]
Right. Add `?user=USER&upload-token=TOKEN` to the end of the target url

**Comment by SunburntRock89** [comment]
oh, I probably should've mentioned, for some reason, those aren't headers, they're in the body

**Comment by SunburntRock89** [comment]
Well, not according to the sharex autogen ![](http://dash.works.wtf/oh/wait/no/it/doesnt/7501f.png)

**Comment by ArsenArsen** [comment]
https://developer.mozilla.org/en-US/docs/Web/HTTP/Headers
https://en.wikipedia.org/wiki/URL#Syntax

ShareX' arguments are actually just query string components.

**Comment by linkjay** [comment]
You seem new to this Sunburnt. Although your problem seems to be resolved for the most part, I still feel like you can learn about common etiquette. 

This is the Github Issues section. There's one for each repo. People with specific rights within the repo may moderate this part. Usually, these are developers. This section is mainly to provide support from the devs. When the ask you a question, you answer it. You don't put "Maybe ;)". Another thing is you're going to have to provide us with more. Error logs if you have an error, your backend receiving code, etc. Nobody can help you if you're sending stuff that won't help. You send a picture of the response which gave us absolutely nothing. When asked about your backend, you didn't give an answer. The guy giving support just made a lucky guess about your situation.

Bottom-line, you would be wise to help us help you by providing more information, and acting better than that.

**Comment by SunburntRock89** [comment]
I think you'll find I'm not new to this. The whole thing about the emoji? This is a Screenshotting program, not the US Nuclear Launch Codes. And I didn't send the response, I sent the request. That was exactly what you had to send to the server.

**Comment by SunburntRock89** [comment]
What kind of person do you take me for? A stupid one? Why would I send the response. Common sense.
